<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>async函数</title>
</head>
<body>
    <script>
        //async
        async function fn(){
            //返回一个字符串
            // return '尚硅谷';//Promise {<fulfilled>: '尚硅谷'}

            //返回的结果不是一个promise对象，则返回的结果就是成功promise对象
            // return;//Promise {<fulfilled>: undefined}

            //抛出错误，返回的结果是一个的promise对象
            // throw new Error("出错啦");//Promise {<rejected>: Error: 出错啦

            //返回的结果是一个promise对象
            return new Promise((resolve,reject) => {
                // resolve('成功的数据');//结果是成功的promise对象
                reject('失败的错误');//失败的promise对象
            });
        }
        //总结：返回结果是一个promise对象，返回结果由函数内部的return语句决定.作用跟then差不多
        //返回的结果不是一个promise对象，则返回的结果就是成功promise对象
        //返回的结果是一个promise对象,则返回结果由该promise对象的结果决定

        const result = fn();

        //调用 then 方法
        result.then(value =>{
            console.log(value);
        },reason => {
            console.warn(reason);
        })
        console.log(result);
    </script>
</body>
</html>